from telegram import Bot, InputMediaPhoto
from apscheduler.schedulers.blocking import BlockingScheduler
from datetime import datetime, timedelta
import pytz
import os

# ====== CONFIG ======
BOT_TOKEN = "8492868444:AAEdwQLkyk8tI23n6faJ6sYMnLxh5XN0Ew4"
CHANNEL_ID = "@shoppeboom"  # Your channel username
TIMEZONE = pytz.timezone('Asia/Yerevan')  # Armenia timezone

bot = Bot(token=BOT_TOKEN)
scheduler = BlockingScheduler()

# ====== TEXT & IMAGE POSTS SCHEDULE ======
posts = [
    {"date": "2025-12-11", "time": "23:59", "content": "👔 HUGE SAVINGS! Get 37% OFF the Hugo Boss Energy Chrono! 👔\n\nCommand respect with the **Hugo Boss 1513970 Energy Chronograph**. This is original, sophisticated BOSS style at a massive discount—perfect for the modern professional.\n\n* **Brand:** 100% Original Hugo Boss\n* **Style:** High-Performance Chronograph\n* **Benefit:** **37% Discount** off the Regular Price!\n* **Value:** Premium design without the premium cost.\n\n**Tap below to grab this powerful timepiece now:**\nhttps://shoppeboom.com/product/brand/hugo-boss", "images": ["11b1.webp", "11b2.webp"]},

    {"date": "2025-12-12", "time": "11:00", "content": "👔 LIMITED DEAL: Save 27% on the Hugo Boss Associate Watch! 👔\n\nElevate your professional image with the sleek **Hugo Boss 1513975 Associate Watch**. Get sophisticated, 100% original BOSS style with an impressive **27% Discount** off the retail price.\n\n* **Brand:** 100% Original Hugo Boss\n* **Style:** Associate Series (Perfect for Business)\n* **Benefit:** **27% Discount** - Unbeatable Value!\n* **Value:** Make a powerful statement for less.\n\n**Tap below to secure this essential BOSS timepiece:**\nhttps://shoppeboom.com/product/brand/hugo-boss", "images": ["12a1.webp", "12a2.webp","12a3.webp"]},
    {"date": "2025-12-12", "time": "17:00", "content": "🚨 POWER DEAL: Huge 37% OFF the Hugo Boss Santiago Chrono! 🚨\n\nUpgrade your wristwear with the high-performance **Hugo Boss 1513936 Santiago Chronograph**. Get sophisticated, 100% original BOSS style with an immediate **37% Discount**!\n\n* **Brand:** 100% Original Hugo Boss\n* **Style:** Santiago Chronograph (Bold Design)\n* **Benefit:** **37% Discount** - Premium quality, exceptional savings.\n\n**Tap below to secure this essential BOSS timepiece:**\nhttps://shoppeboom.com/product/brand/hugo-boss", "images": ["12b1.webp", "12b2.webp","12b3.webp"]},

    {"date": "2025-12-13", "time": "01:00", "content": "⚫️ COMMAND ATTENTION: Hugo Boss Admiral Black Chronograph! ⚫️\n\nOwn the ultimate statement piece. The **Hugo Boss 1513966 Admiral Black Chronograph** delivers powerful, sophisticated design—now available at an exclusive discount.\n\n* **Brand:** 100% Original Hugo Boss\n* **Style:** Admiral Black Chronograph (Maximum Impact)\n* **Benefit:** **Exclusive Discount** Off Retail Price!\n* **Value:** Luxury Black-Out Style for Less.\n\n**Tap below to claim your original BOSS timepiece:**\nhttps://shoppeboom.com/product/brand/hugo-boss", "images": ["13a1.webp", "13a2.webp","13a3.webp"]},
    {"date": "2025-12-13", "time": "17:00", "content": "🇺🇸 CLASSIC AMERICAN STYLE: New Tommy Hilfiger Watch Drop! 🇺🇸\n\nInstantly upgrade your casual and professional look with the **Tommy Hilfiger 1791948 Multi Dial Watch**. Get that signature preppy style and quality craftsmanship today.\n\n* **Brand:** 100% Original Tommy Hilfiger\n* **Style:** Multi-Dial Quartz Men's Watch\n* **Feature:** Signature sporty yet refined look\n* **💰 SALE PRICE:** **[Insert Sale Price Here] USD** (Unbeatable Value!)\n\n**Tap below to grab this essential accessory:**\nhttps://shoppeboom.com/product/brand/tommy-hilfiger", "images": ["13b1.webp", "13b2.webp"]},

    {"date":"2025-12-14","time":"21:00","content":"✨ FRESH ARRIVAL: Tommy Hilfiger 1791790 Men's Watch! ✨ Elevate your casual sophistication with this essential timepiece from Tommy Hilfiger. Get that iconic American cool look with 100% original quality. Brand: 100% Original Tommy Hilfiger. Style: Signature Men's Analogue Watch. Feature: Designed for effortless everyday style. Sale price or discount available. Tap below to grab your new Tommy Hilfiger watch: https://shoppeboom.com/product/brand/tommy-hilfiger","images":["14a2.webp","14a1.webp"]},
    {"date":"2025-12-14","time":"00:22","content":"🚨 HALF PRICE LUXURY! Save 48% on Tommy Hilfiger Gold Mesh! 🚨 Elevate your everyday style with the stunning Tommy Hilfiger 1782302 Ladies Blake Watch. Enjoy the elegant gold mesh design and a massive 48% Discount off the retail price! Brand: 100% Original Tommy Hilfiger. Style: Elegant Gold Mesh Strap. Benefit: HUGE 48% Discount - Nearly half off. Feature: Timeless and sophisticated look. Tap below to claim this highly discounted luxury piece: https://shoppeboom.com/product/brand/tommy-hilfiger","images":["14b1.webp","14b2.webp","14b3.webp"]},

    {"date":"2025-12-15","time":"11:00","content":"🔥 Step Up Your Style Game!\n\nMeet the CHIKO Chumani Square Toe Block Heels Loafers – where comfort meets bold elegance. Perfect for power moves at work or turning heads on a night out. 👠✨\n\nWhy you’ll love them:\n• Chic square toe design ✅\n• Stable block heels for all-day confidence 💃\n• Effortless style for every outfit 🌟\n\nDon’t wait – your new favorite shoes are just a click away!\n\n👉 Shop Now on ChikoShoes: https://www.chikoshoes.com/shop/chiko-chumani-square-toe-block-heels-loafers-shoes/?aw_affid=2091833&awc=24111_1765449536_a7692c1d539dfab28c3039e09f20d408\n\nOr explore more styles here: https://shoppeboom.com/","images":["15a1.jpg","15a2.jpg","15a3.jpg"]},
    {"date":"2025-12-14","time":"00:16","content":"🔥 Elevate Your Style with CHIKO Christina Square Toe Stiletto Boots!\n\nStep out with confidence in these sleek stiletto boots – perfect for day-to-night looks and making a statement wherever you go. 👢✨\n\nWhy you’ll love them:\n• Chic square toe design ✅\n• Elegant stiletto heels for bold style 💃\n• Perfect match for dresses, jeans, or office outfits 🌟\n\nDon’t wait – grab your new favorite boots now!\n\n👉 Shop Now on ChikoShoes: https://www.chikoshoes.com/shop/chiko-christina-square-toe-stiletto-boots/?aw_affid=2091833&awc=24111_1765449852_08bf985f3e4c443d17231f36f774edb3\n\nOr explore more styles here: https://shoppeboom.com/","images":["15b1.jpg","15b2.jpg","15b3.jpg"]},
    
    {"date":"2025-12-16","time":"11:00","content":"🔥 Step Up Your Style with CHIKO Cinnamon Square Toe Block Heels T-Strap Shoes!\n\nWalk with confidence and flair in these chic T-Strap block heels – perfect for both office days and stylish evenings out. 👠✨\n\nWhy you’ll love them:\n• Elegant square toe design ✅\n• Comfortable block heels for all-day wear 💃\n• Versatile style that pairs with dresses, skirts, or pants 🌟\n\nDon’t wait – grab your favorite pair now!\n\n👉 Shop Now on ChikoShoes: https://www.chikoshoes.com/shop/chiko-cinnamon-square-toe-block-heels-t-strap-shoes/?aw_affid=2091833&awc=24111_1765450333_51c8ec9de419f94f40b44ddbe4026e5e\n\nOr explore more styles here: https://shoppeboom.com/new","images":["16a1.jpg","16a2.jpg","16a3.jpg"]},
    {"date":"2025-12-16","time":"17:00","content":"🔥 Step Out in Style with CHIKO Chum Pointy Toe Block Heels Ankle Boots!\n\nElevate your outfit with these sleek ankle boots – perfect for workdays, nights out, or any occasion you want to make a statement. 👢✨\n\nWhy you’ll love them:\n• Chic pointy toe design ✅\n• Comfortable block heels for all-day wear 💃\n• Versatile style that pairs with skirts, jeans, or dresses 🌟\n\nDon’t wait – grab your new favorite boots now!\n\n👉 Shop Now on ChikoShoes: https://www.chikoshoes.com/shop/chiko-chum-pointy-toe-block-heels-ankle-boots/?aw_affid=2091833&awc=24111_1765450534_9f8077e5fd0ff259129efc1f91961fc0\n\nOr explore more styles here: https://shoppeboom.com/new","images":["16b1.jpg","16b2.jpg","16b3.jpg"]},
    {"date":"2025-12-16","time":"23:59","content":"🔥 Step Into Comfort and Style with CHIKO Chrissy Round Toe Block Heels Ankle Boots!\n\nThese chic ankle boots feature a suede upper, synthetic lining, and durable rubber sole – perfect for everyday wear or stylish nights out. 👢✨\n\nWhy you’ll love them:\n• Elegant round toe design ✅\n• Low block heel approx. 0.5\" (1 cm) for all-day comfort 💃\n• Versatile style for jeans, skirts, or dresses 🌟\n\nDon’t wait – grab your new favorite boots now!\n\n👉 Shop Now on ChikoShoes: https://www.chikoshoes.com/shop/chiko-chrissy-round-toe-block-heels-ankle-boots/?aw_affid=2091833&awc=24111_1765451053_0058fef75afe960c05d5e1a2d20b6c82","images":["16c1.jpg","16c2.jpg","16c3.jpg"]},    

    {"date":"2025-12-17","time":"11:00","content":"🔥 Elevate Your Wrist Game with Versace Hellenyium Black Dial Men's Watch!\n\nExperience the perfect blend of luxury and style with this sleek Versace timepiece – designed for confident, modern men. ⌚✨\n\nWhy you’ll love it:\n• Bold, sophisticated black dial ✅\n• Premium craftsmanship for lasting quality 💎\n• Versatile design for both casual and formal wear 🌟\n\nDon’t wait – make a statement on your wrist now!\n\n👉 Shop Now on WatchesOfUSA: https://watchesofusa.com/products/versace-vevk00420-hellenyium-black-dial-mens-watch?variant=42924379504694&utm_source=AWIN&utm_medium=AWIN&source=aw&utm_id=2091833_&utm_campaign=affiliate&aw_affid=2091833&awc=116479_1765451836_038eab4b4ffa4cee8c900927585ec9e2\n\nOr explore more styles here: https://shoppeboom.com/product/brand/versace","images":["17a1.webp","17a2.webp","17a3.webp"]},
    {"date":"2025-12-17","time":"17:00","content":"✨ Shine Bright with Versace Hellenyium Quartz Silver Dial Ladies Watch! ✨\n\nElevate your elegance with this stunning Versace timepiece – perfect for formal occasions or everyday sophistication. ⌚💎\n\nWhy you’ll love it:\n• Sleek silver dial design ✅\n• Premium craftsmanship for lasting quality 💖\n• Versatile style that complements any outfit 🌟\n\nDon’t wait – add luxury to your wrist today!\n\n👉 Shop Now on WatchesOfUSA: https://watchesofusa.com/products/versace-v12030015-hellenyium-quartz-silver-dial-ladies-watch?variant=42924378259510&utm_source=AWIN&utm_medium=AWIN&source=aw&utm_id=2091833_&utm_campaign=affiliate&aw_affid=2091833&awc=116479_1765452004_68e1dea9bf11bcdd0df7b0ad3ff4660d\n\nOr explore more styles here: https://shoppeboom.com/product/brand/versace","images":["17b1.webp","17b2.webp"]},
    {"date":"2025-12-17","time":"21:00","content":"🔥 Upgrade Your Style with Tommy Hilfiger Multi Dial Quartz Men's Watch! 🔥\n\nStep up your wrist game with this sleek, versatile timepiece – perfect for everyday wear or making a statement at work. ⌚✨\n\nWhy you’ll love it:\n• Multi-dial design for precise timekeeping ✅\n• Premium craftsmanship for long-lasting quality 💎\n• Versatile style that pairs with any outfit 🌟\n\nDon’t wait – add this watch to your collection today!\n\n👉 Shop Now on WatchesOfUSA: https://watchesofusa.com/products/tommy-hilfiger-1791948-multi-dial-quartz-mens-watch?variant=42924378030134&utm_source=AWIN&utm_medium=AWIN&source=aw&utm_id=2091833_&utm_campaign=affiliate&aw_affid=2091833&awc=116479_1765452323_b4654c54ba2b2061807b286c0d116dd6\n\nOr explore more styles here: https://shoppeboom.com/product/brand/tommy-hilfiger","images":["17c1.webp","17c2.webp","17c3.webp"]},

    {"date":"2025-12-18","time":"11:00","content":"🔥 Elevate Your Style with Tommy Hilfiger Men's Watch! 🔥\n\nStep up your wrist game with this sleek and versatile timepiece – perfect for everyday wear or making a statement at work. ⌚✨\n\nWhy you’ll love it:\n• Classic and sophisticated design ✅\n• Premium craftsmanship for long-lasting quality 💎\n• Versatile style that pairs with any outfit 🌟\n\nDon’t wait – add this watch to your collection today!\n\n👉 Shop Now on WatchesOfUSA: https://watchesofusa.com/products/tommy-hilfiger-1791791-mens-watch?variant=42924377866294&utm_source=AWIN&utm_medium=AWIN&source=aw&utm_id=2091833_&utm_campaign=affiliate&aw_affid=2091833&awc=116479_1765452764_1e45ceb7de882f11a5b7e91cc3f881bf\n\nOr explore more styles here: https://shoppeboom.com/product/brand/tommy-hilfiger","images":["18a1.webp","18a2.webp","18a3.webp"]},
    {"date":"2025-12-18","time":"17:00","content":"🔥 Upgrade Your Look with Tommy Hilfiger Damon Men's Watch! 🔥\n\nStep up your style with this sleek and sophisticated timepiece – perfect for everyday wear or making a bold statement. ⌚✨\n\nWhy you’ll love it:\n• Classic and elegant design ✅\n• Premium craftsmanship for lasting quality 💎\n• Versatile style that complements any outfit 🌟\n\nDon’t wait – add this watch to your collection today!\n\n👉 Shop Now on WatchesOfUSA: https://watchesofusa.com/products/tommy-hilfiger-1791415-damon-mens-watch?variant=42924376490038&utm_source=AWIN&utm_medium=AWIN&source=aw&utm_id=2091833_&utm_campaign=affiliate&aw_affid=2091833&awc=116479_1765453449_1553bf016918a8c3ec989c5f7b49e939\n\nOr explore more styles here: https://shoppeboom.com/product/brand/tommy-hilfiger","images":["18b1.webp","18b2.webp","18b3.webp"]},
    {"date":"2025-12-18","time":"23:59","content":"🌟 Cozy & Stylish: Isaac Mizrahi Boys' Velvet Quilt 2-20 Peacock - Charcoal! 🌟\n\nKeep your little ones warm and trendy with this premium velvet quilted jacket – perfect for school, outings, or special occasions. 🧒✨\n\nWhy you’ll love it:\n• Soft velvet material for comfort ✅\n• Trendy peacock & charcoal color combo 🌈\n• Durable design for everyday adventures 💪\n\nDon’t wait – upgrade your kid’s wardrobe today!\n\n👉 Shop Now on Albertonardoni: https://albertonardoni.com/products/isaac-mizrahi-boys-velvet-quilt-2-20-peacock-charcoal?variant=37592938545348&source=aw&utm_source=awin&utm_id=2091833_&utm_campaign=affiliate&aw_affid=2091833&awc=102429_1765453679_6f8482eedad1be6adff7f1bec198535e\n\nOr explore more styles here: https://shoppeboom.com/product/brand/style-brooklyn","images":["18c1.jpg"]},

    {"date":"2025-12-19","time":"11:00","content":"✨ Sleek & Timeless: Michael Kors Slim Runway Three-Hand Ladies Watch! ✨\n\nStep up your style with this elegant ladies' watch – perfect for daily wear or adding sophistication to any outfit. ⌚💖\n\nWhy you’ll love it:\n• Slim runway design for a modern, chic look ✅\n• Premium craftsmanship for long-lasting quality 💎\n• Versatile style for work, events, or casual days 🌟\n\nDon’t wait – make this watch yours today!\n\n👉 Shop Now on WatchesOfUSA: https://watchesofusa.com/products/michael-kors-mk4540-slim-runway-three-hand-ladies-watch?variant=42924367577142&utm_source=AWIN&utm_medium=AWIN&source=aw&utm_id=2091833_&utm_campaign=affiliate&aw_affid=2091833&awc=116479_1765453995_f9de90df1d4fb49bf5c46b1fabf48883\n\nOr explore more styles here: https://shoppeboom.com/product/brand/michael-kors","images":["19a1.webp","19a2.webp","19a3.webp"]},
    {"date":"2025-12-19","time":"17:00","content":"✨ Elegant & Chic: Michael Kors Darci Quartz Women's Watch! ✨\n\nUpgrade your wrist game with this stylish ladies' watch – perfect for everyday wear or special occasions. ⌚💖\n\nWhy you’ll love it:\n• Sleek Darci quartz design for a modern, refined look ✅\n• Premium craftsmanship for lasting quality 💎\n• Versatile style that complements any outfit 🌟\n\nDon’t wait – add this watch to your collection today!\n\n👉 Shop Now on WatchesOfUSA: https://watchesofusa.com/products/michael-kors-mk3402-darci-quartz-womens-watch?variant=42924366299190&utm_source=AWIN&utm_medium=AWIN&source=aw&utm_id=2091833_&utm_campaign=affiliate&aw_affid=2091833&awc=116479_1765454098_0adcf082d20db83d85ece33c38433588\n\nOr explore more styles here: https://shoppeboom.com/product/brand/michael-kors","images":["19b1.webp","19b2.webp","19b3.webp"]},
    
    {"date":"2025-12-20","time":"01:00","content":"✨ Sleek & Chic: Michael Kors Darci Ladies Watch! ✨\n\nAdd elegance to your wrist with this stunning ladies' watch – perfect for daily wear or special occasions. ⌚💖\n\nWhy you’ll love it:\n• Elegant Darci design for a modern, refined look ✅\n• Premium craftsmanship for long-lasting quality 💎\n• Versatile style that complements any outfit 🌟\n\nDon’t wait – make this watch yours today!\n\n👉 Shop Now on WatchesOfUSA: https://watchesofusa.com/products/michael-kors-mk3779-darci-ladies-watch?variant=42924366790710&utm_source=AWIN&utm_medium=AWIN&source=aw&utm_id=2091833_&utm_campaign=affiliate&aw_affid=2091833&awc=116479_1765455407_d23f482e46958bda5760d0c8844bcd55\n\nOr explore more styles here: https://shoppeboom.com/product/brand/michael-kors","images":["20a1.webp","20a2.webp","20a3.webp"]},
    {"date":"2025-12-20","time":"17:00","content":"✨ Stylish & Comfortable: Marc Jacobs Baker Ladies Watch! ✨\n\nUpgrade your wrist game with this chic ladies' watch – perfect for daily wear or adding a touch of elegance to any outfit. ⌚💖\n\nWhy you’ll love it:\n• Sleek Baker design for a modern, refined look ✅\n• Premium craftsmanship for lasting quality 💎\n• Versatile style that pairs with any outfit 🌟\n\nDon’t wait – add this watch to your collection today!\n\n👉 Shop Now on WatchesOfUSA: https://watchesofusa.com/products/marc-jacobs-mbm1266-baker-ladies-watch?variant=42924361875510&utm_source=AWIN&utm_medium=AWIN&source=aw&utm_id=2091833_&utm_campaign=affiliate&aw_affid=2091833&awc=116479_1765455562_ee0b9148f6e66a03062cf44bafc0a090\n\nOr explore more styles here: https://shoppeboom.com/product/brand/marc-jacobs","images":["20b1.webp","20b2.webp","20b3.webp"]},

    {"date":"2025-12-21","time":"11:00","content":"✨ Elegant & Chic: Marc Jacobs Women's Watch! ✨\n\nUpgrade your wrist style with this stunning ladies' watch – perfect for daily wear or special occasions. ⌚💖\n\nWhy you’ll love it:\n• Sleek MBM3329 design for a modern, refined look ✅\n• Premium craftsmanship for lasting quality 💎\n• Versatile style that pairs with any outfit 🌟\n\nDon’t wait – add this watch to your collection today!\n\n👉 Shop Now on WatchesOfUSA: https://watchesofusa.com/products/marc-jacobs-mbm3329-womens-watch?variant=42924362825782&utm_source=AWIN&utm_medium=AWIN&source=aw&utm_id=2091833_&utm_campaign=affiliate&aw_affid=2091833&awc=116479_1765455656_7d390236ff72b322152b5eebe5304d56\n\nOr explore more styles here: https://shoppeboom.com/product/brand/marc-jacobs","images":["21a1.webp","21a2.webp","21a3.webp"]},
    {"date":"2025-12-21","time":"17:00","content":"✨ Chic & Modern: March by March Jacobs Women's Wrist Watch! ✨\n\nUpgrade your style with this elegant ladies' watch – perfect for everyday wear or adding a sophisticated touch to any outfit. ⌚💖\n\nWhy you’ll love it:\n• Sleek MBM3056 design for a modern, refined look ✅\n• Premium craftsmanship for long-lasting quality 💎\n• Versatile style that complements any outfit 🌟\n\nDon’t wait – make this watch yours today!\n\n👉 Shop Now on WatchesOfUSA: https://watchesofusa.com/products/march-by-march-jacobs-mbm3056-wrist-watch-womens?variant=42924363710518&utm_source=AWIN&utm_medium=AWIN&source=aw&utm_id=2091833_&utm_campaign=affiliate&aw_affid=2091833&awc=116479_1765455809_d2788cedd07df7c53e265ce78c4f4135\n\nOr explore more styles here: https://shoppeboom.com/product/brand/marc-jacobs","images":["21b1.webp","21b2.webp"]},

    {"date":"2025-12-22","time":"02:00","content":"✨ Elegant & Modern: Marc Jacobs Women's Watch! ✨\n\nUpgrade your wrist style with this chic ladies' watch – perfect for daily wear or adding a touch of elegance to any outfit. ⌚💖\n\nWhy you’ll love it:\n• Sleek MBM1400 design for a refined, modern look ✅\n• Premium craftsmanship for long-lasting quality 💎\n• Versatile style that complements any outfit 🌟\n\nDon’t wait – add this watch to your collection today!\n\n👉 Shop Now on WatchesOfUSA: https://watchesofusa.com/products/marc-jacobs-mbm1400-womens-watch?variant=42924361941046&utm_source=AWIN&utm_medium=AWIN&source=aw&utm_id=2091833_&utm_campaign=affiliate&aw_affid=2091833&awc=116479_1765456120_29805409fb0277ee0e0d97e52f4d541a\n\nOr explore more styles here: https://shoppeboom.com/product/brand/marc-jacobs","images":["22a1.webp","22a2.webp","22a3.webp"]},
    {"date":"2025-12-22","time":"17:00","content":"✨ Elegant & Stylish: Marc Jacobs Baker Gold Green Dial Ladies Watch! ✨\n\nUpgrade your wrist style with this stunning ladies' watch – perfect for everyday wear or adding a sophisticated touch to any outfit. ⌚💖\n\nWhy you’ll love it:\n• Sleek MBM3245 Baker design with Gold & Green Dial ✅\n• Premium craftsmanship for long-lasting quality 💎\n• Versatile style that pairs with any outfit 🌟\n\nDon’t wait – make this watch yours today!\n\n👉 Shop Now on WatchesOfUSA: https://watchesofusa.com/products/marc-jacobs-mbm3245-baker-gold-green-dial-ladies-watch?variant=42924362498102&utm_source=AWIN&utm_medium=AWIN&source=aw&utm_id=2091833_&utm_campaign=affiliate&aw_affid=2091833&awc=116479_1765456231_ba5a14d69dc7b3b4c301a6def7b241d0\n\nOr explore more styles here: https://shoppeboom.com/product/brand/marc-jacobs","images":["22b1.webp","22b2.webp"]},

    {"date":"2025-12-23","time":"02:00","content":"✨ Sophisticated & Bold: Hugo Boss Center Court Lux Men's Watch! ✨\n\nElevate your style with this premium men's watch – perfect for everyday elegance or special occasions. ⌚💎\n\nWhy you’ll love it:\n• Sleek Center Court Lux design for a refined, modern look ✅\n• Premium craftsmanship for lasting quality 💎\n• Versatile style that pairs with any outfit 🌟\n\nDon’t wait – add this luxury watch to your collection today!\n\n👉 Shop Now on WatchesOfUSA: https://watchesofusa.com/products/hugo-boss-1514027-center-court-lux-mens-watch?variant=42924361187382&utm_source=AWIN&utm_medium=AWIN&source=aw&utm_id=2091833_&utm_campaign=affiliate&aw_affid=2091833&awc=116479_1765456384_b6f732a7900b38825425cbe6aa9dda66\n\nOr explore more styles here: https://shoppeboom.com/product/brand/hugo-boss","images":["23a1.webp","23a2.webp","23a3.webp"]},
    {"date":"2025-12-23","time":"17:00","content":"✨ Sleek & Powerful: Hugo Boss Taper Chronograph Men's Watch! ✨\n\nUpgrade your style with this bold men's chronograph – perfect for daily elegance or making a statement at any occasion. ⌚💎\n\nWhy you’ll love it:\n• Sharp Taper Chronograph design for a modern, refined look ✅\n• Premium craftsmanship for lasting quality 💎\n• Versatile style that pairs with any outfit 🌟\n\nDon’t wait – make this luxury watch yours today!\n\n👉 Shop Now on WatchesOfUSA: https://watchesofusa.com/products/hugo-boss-1514087-taper-chronograph-men-s-watch?variant=42924361515062&utm_source=AWIN&utm_medium=AWIN&source=aw&utm_id=2091833_&utm_campaign=affiliate&aw_affid=2091833&awc=116479_1765456466_7aa0ce5710e479828d0aab2c2e1f32a5\n\nOr explore more styles here: https://shoppeboom.com/product/brand/hugo-boss","images":["23b1.webp","23b2.webp"]},

    {"date":"2025-12-24","time":"02:00","content":"✨ Elegant & Refined: Hugo Boss Center Court Bronze Dial Men's Watch! ✨\n\nElevate your style with this premium men's watch – perfect for daily elegance or special occasions. ⌚💎\n\nWhy you’ll love it:\n• Sleek Center Court Bronze design for a modern, sophisticated look ✅\n• Premium craftsmanship for lasting quality 💎\n• Versatile style that pairs with any outfit 🌟\n\nDon’t wait – make this luxury watch yours today!\n\n👉 Shop Now on WatchesOfUSA: https://watchesofusa.com/products/hugo-boss-1514024-center-court-bronze-dial-mens-watch?variant=42924361089078&utm_source=AWIN&utm_medium=AWIN&source=aw&utm_id=2091833_&utm_campaign=affiliate&aw_affid=2091833&awc=116479_1765456718_c4ad504eb19a7436f5b6dafbecbe6671\n\nOr explore more styles here: https://shoppeboom.com/product/brand/hugo-boss","images":["24a1.webp","24a2.webp","24a3.webp"]},
    {"date":"2025-12-24","time":"11:00","content":"✨ Chic & Bold: CHIKO Abigail Pointy Toe Wedge Knee High Boots! ✨\n\nStep up your style with these stunning knee-high boots – perfect for any outfit or occasion. 👢💖\n\nWhy you’ll love them:\n• Sleek Abigail Wedge design for a modern, elegant look ✅\n• Premium craftsmanship for lasting quality 💎\n• Comfortable fit with versatile style 🌟\n\nDon’t wait – make these boots yours today!\n\n👉 Shop Now on Chiko Shoes: https://www.chikoshoes.com/shop/chiko-abigail-pointy-toe-wedge-knee-high-boots/?aw_affid=2091833&awc=24111_1765456834_9516e63a087f1f6f9e64fd94c79138b3\n\nOr explore more styles here: https://shoppeboom.com/product/brand/chiko","images":["24b1.jpg","24b2.jpg","24b3.jpg"]},
    {"date":"2025-12-24","time":"19:00","content":"✨ Elegant & Chic: CHIKO Icess Pointy Toe Kitten Heels Knee High Boots! ✨\n\nStep into style with these gorgeous knee-high boots – perfect for adding a sophisticated touch to any outfit. 👢💖\n\nWhy you’ll love them:\n• Sleek Icess Pointy Toe Kitten Heels design for a refined, modern look ✅\n• Premium leather craftsmanship with durable synthetic lining 💎\n• Comfortable 1\" (3 cm) heel and versatile style 🌟\n\nDon’t wait – grab these boots today!\n\n👉 Shop Now on Chiko Shoes: https://www.chikoshoes.com/shop/chiko-icess-pointy-toe-kitten-heels-knee-high-boots/?aw_affid=2091833&awc=24111_1765457056_c5c77a73d61074860cc2e3744c1172cb\n\nOr explore more styles here: https://shoppeboom.com/product/brand/chiko","images":["24c1.jpg","24c2.jpg","24c3.jpg"]},

]

# ====== FUNCTION TO SEND POSTS ======
def send_post(post):
    try:
        if "images" in post and post["images"]:
            # If multiple images, send as album
            if len(post["images"]) > 1:
                media_group = []
                for idx, img_file in enumerate(post["images"]):
                    if os.path.exists(img_file):
                        if idx == 0:
                            media_group.append(InputMediaPhoto(open(img_file, "rb"), caption=post["content"]))
                        else:
                            media_group.append(InputMediaPhoto(open(img_file, "rb")))
                if media_group:
                    bot.send_media_group(chat_id=CHANNEL_ID, media=media_group)
            else:
                # Single image
                img_file = post["images"][0]
                if os.path.exists(img_file):
                    with open(img_file, "rb") as photo:
                        bot.send_photo(chat_id=CHANNEL_ID, photo=photo, caption=post["content"])
                else:
                    bot.send_message(chat_id=CHANNEL_ID, text=post["content"])
        else:
            # Text only
            bot.send_message(chat_id=CHANNEL_ID, text=post["content"])

        print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] Posted: {post['content']}")
    except Exception as e:
        print(f"Failed to post {post['content']}: {e}")


# ====== SCHEDULE JOBS ======
for post in posts:
    # Convert string date to real datetime
    post_date = datetime.strptime(post["date"], "%Y-%m-%d")
    hour, minute = map(int, post["time"].split(":"))

    # Schedule EXACT date + time
    scheduler.add_job(
        send_post,
        'cron',
        year=post_date.year,
        month=post_date.month,
        day=post_date.day,
        hour=hour,
        minute=minute,
        args=[post],
        timezone=TIMEZONE,
        misfire_grace_time=300
    )



# ====== START BOT ======
print("Bot is running and will post messages automatically...")
scheduler.start()